# Site settings
title: Jack Lundeen
email: brigette.lundeen@gmail.com
description: This site is all for my little man Jack!
baseurl: "/jack/" # the subpath of your site, e.g. /blog/
url: "http://codepretty.github.io" # the base hostname & protocol for your site
twitter_username: codepretty
github_username:  codepretty


# Build settings
highlighter: true
markdown: kramdown
permalink: pretty